### ISSUE TITLE
Add compiled release

### ISSUE THREAD

**Issue by Keith94** [crosire/d3d8to9#10]
Can you add latest compiled DLL to [releases page](https://github.com/crosire/d3d8to9/releases)? Thanks.

**Comment by crosire** [comment]
A compiled DLL can be found here: https://reshade.me/d3d8to9

**Comment by Keith94** [comment]
Hmm, mediafire is not the most convenient IMO, the website itself being full of popup ads, etc.

I think it's better to upload directly on GitHub releases page, where people can find the source as well.

**Comment by crosire** [comment]
Oh, didn't realize that was still hosted on Mediafire. Was supposed to be hosted on my own server.

**Comment by Keith94** [comment]
Okay that works, thanks. :)
