### ISSUE TITLE
Chaser (CloakNT v1.x) v1.50 [Steam] - No Launch

### ISSUE THREAD

**Issue by Saijin-Naib** [crosire/d3d8to9#102]
Chaser will not launch properly with the crosire build of the d3d8to9 dll and Reshade, though I can get it to launch properly using the elishacloud version of the d3d8to9+dxwrapper dlls.

I'd like to see if Chaser would benefit from ReShade, but I can't figure out what is causing it to not launch using the proper DLL.

**Comment by crosire** [comment]
Does it work without ReShade? If so it's not a problem with d3d8to9 and not a relevant issue here.

**Comment by Saijin-Naib** [comment]
No, with just the d3d8.dll in the game's root next to the exe the game fails to launch. This behavior is contrary to using the DxWrapper version.

ReShade also doesn't appear to recognize the dll being in the game's folder next to the exe, as it prompts me to re-download it every time I launch Reshade.

**Comment by Saijin-Naib** [comment]
Hmm,
Using the DxWrapper files along with Reshade yields a working install of ReShade, but not so with the Reshade provided d3d8.dll

![20190901223402_1](https://user-images.githubusercontent.com/19295950/64086930-d7796380-cd08-11e9-8231-245958e72bdc.jpg)
Reshade control panel showing

![20190901223426_1](https://user-images.githubusercontent.com/19295950/64086931-d7796380-cd08-11e9-84a8-57720e6abd9d.jpg)
Testing with ASCII effect

**Comment by elishacloud** [comment]
It is possible that this game requires other exports.  D3d8to9 only has one exported function, while dxwrapper exports all of the d3d8 functions.

Try with this dll, I quickly added all exported functions to the d3d8to9 code: [d3d8.zip](https://github.com/crosire/d3d8to9/files/3564302/d3d8.zip)

**Comment by Saijin-Naib** [comment]
Hmm, interesting.

Even with the latest dll, it still silently fails to launch.

Do you have Steam? I can gift you a copy if that'll be easier for you to debug with.

**Comment by elishacloud** [comment]
Yes, I have a Steam account.

**Comment by Saijin-Naib** [comment]
I sent you an email regarding my prior post.

**Comment by Saijin-Naib** [comment]
Latest version (1.9.2) of d3d8.dll with Reshade 4.4.2 yields a (mostly) working setup.

Vanilla Chaser:  
![39670_20191123011716_1](https://user-images.githubusercontent.com/19295950/69474504-07785600-0d90-11ea-97b6-24dbfaad8d8b.png)

![39670_20191123015748_1](https://user-images.githubusercontent.com/19295950/69474946-20373a80-0d95-11ea-9b44-35dd3f57d158.png)

Having way too much fun with Reshade 4.4.2
![39670_20191123011652_1](https://user-images.githubusercontent.com/19295950/69474503-07785600-0d90-11ea-9628-e16576ddf0c7.png)

![39670_20191123015815_1](https://user-images.githubusercontent.com/19295950/69474947-20373a80-0d95-11ea-8623-4d56bde64266.png)

Depth Buffer not working, but Normal Buffer is?
![39670_20191123020246_1](https://user-images.githubusercontent.com/19295950/69475010-c8e59a00-0d95-11ea-96af-7c12968bedc0.png)

**Comment by crosire** [comment]
Depth is working fine: You just need to set RESHADE_DEPTH_INPUT_IS_REVERSED to 0.

**Comment by Saijin-Naib** [comment]
> Depth is working fine: You just need to set RESHADE_DEPTH_INPUT_IS_REVERSED to 0.

You're right. The difficulty I seem to be having is that Chaser/CloakNT seemingly create, switch, and destroy depth buffers seemingly at will, so I sometimes have to go into Reshade to manually select the current/real depth buffer.
