### ISSUE TITLE
Generals ZH: Intel GPA reports API Error IDIRECT3D9_CHECKDEVICEFORMAT

### ISSUE THREAD

**Issue by altimumdelta** [crosire/d3d8to9#111]
First off thank you very much for this, without it, running profilers such as AMD GPUPerfStudio and Intel GPA would have been impossible.

So I always get this error when I open up a frame in Intel GPA Frame Analyzer. I thought maybe it's something it's something that has to do with converting DX8 and may be fixable here?

![GenZH_DX8TO9_GPAFrame_API-ERROR_D3D9_CHECKDEVICEFORMAT](https://user-images.githubusercontent.com/48530820/75975825-86c20d80-5ed9-11ea-9dde-7c218b596fd0.png)

[GenZH_API-Log-Export_D3D9_CHECKDEVICEFORMAT_Example1.zip](https://github.com/crosire/d3d8to9/files/4293430/GenZH_API-Log-Export_D3D9_CHECKDEVICEFORMAT_Example1.zip)

**Comment by crosire** [comment]
`D3DFMT_R8G8B8` is not supported on modern hardware, hence why that returns a `D3DERR_NOTAVAILABLE` here. I would expect the same to happen with D3D8. The game apparently checks whether that format is available or not, which it is not. But this is not actually an error. So looks to me like the frame analyzer does not handle this correctly.

**Comment by altimumdelta** [comment]
Oh thanks for a fast response, hopefully no other side effects happen because of this in the results.
