### ISSUE TITLE
please help with d3d8to9.sln

### ISSUE THREAD

**Issue by jr614** [crosire/d3d8to9#112]
ok, once i open the d3d8to9.sln in visual studio what do i do? i'm lost.

**Comment by jr614** [comment]
i have visual studio 2019 if that info helps

**Comment by HerMajestyDrMona** [comment]
What error do you get when you are trying to compile the DLL?

Do you actually edit anything in the source code? If not, you can simply download the compiled d3d8.dll file from: https://github.com/crosire/d3d8to9/releases and paste to the game folder.

Similar question has been answered here: https://github.com/crosire/d3d8to9/issues/37

**Comment by jr614** [comment]
no error, i dont know what to do. i have the d3d8to9.sln file. what do i do with it? I'm trying to play old games with reshade. what do I need?

**Comment by jr614** [comment]
i open the file in visual studio, now what?

**Comment by jr614** [comment]
i have the new d3d8 file you mentioned. i suppose the game just doesn't support it.

**Comment by HerMajestyDrMona** [comment]
What game is it? Have you pasted the downloaded d3d8.dll to the main folder of this game?

**Comment by jr614** [comment]
starship troopers: terran ascendancy. i got your latest file and copied it over the old one. no luck.

**Comment by HerMajestyDrMona** [comment]
It seems like this game was released in 2000, and some sources say it uses an older DirectX version (7A). Therefore, unfortunately d3d8to9 won't work with it. D3d8to9 replaces an existing d3d8.dll to convert API calls into DirectX 9 ones. If the game uses an older DirectX version, with a different dll file - it will not work.

**Comment by jr614** [comment]
thanks for the info

**Comment by elishacloud** [comment]
You might want to check out this page:
https://www.pcgamingwiki.com/wiki/Starship_Troopers:_Terran_Ascendancy

**Comment by jr614** [comment]
yup, it says directx 7. files make it look like directx 8. thats probably because of the modifications I use to even run it, lol, oh well. thanks again.
