### ISSUE TITLE
Graphic issues with Haegemonia Legions of Iron

### ISSUE THREAD

**Issue by elishacloud** [crosire/d3d8to9#12]
Hello,

I have been testing your d3d8to9 code.  Thanks for creating this, it help me get several games working on Windows 10!  However, I found an issue with the game [Haegemonia Legions of Iron](https://www.gog.com/game/haegemonia_gold_edition).  After a bit of troubleshooting I found the issue in your code.  It seems that you set up a default vertex when the Direct3D8::CreateDevice API is called.  This seems to be not needed (based on Micrososft documentation) and it causes a graphics issue with Haegemonia.  I attached an updated d3d8to9_base.cpp file where this issue is fixed.

I also updated the d3d8types.cpp to fix a few minor issues and help with compatibility.  Both of these changes are in the attached zip file.

Thanks,
Elisha

[d3d8to9.zip](https://github.com/crosire/d3d8to9/files/782489/d3d8to9.zip)

**Comment by crosire** [comment]
Could you create a pull request for those changes? That would make discussion so much easier.

**Comment by elishacloud** [comment]
Not quite sure how to create a pull request, I am new to GitHub!  I am sure it is easy, but did not have time to look into it yet.  I will try and create a pull request (once I have some time) to make this easier to discuss.

**Comment by crosire** [comment]
Merged in 0c5e710af79db18cc7c2aa1b2df5b6c4f516aaf3.
