### ISSUE TITLE
Feature request: configurable anti-aliasing

### ISSUE THREAD

**Issue by Akira13641** [crosire/d3d8to9#127]
While I personally prefer d3d8to9 for a variety of reasons (compatibility, performance, etc) one thing it lacks in comparison to [dgVoodoo2](http://dege.freeweb.hu/) is the ability to directly specify that a particular level of multisampling should be used when initializing D3D9.

This would be very beneficial in a number of titles that do not / did not have any in-game way of activating hardware-based anti-aliasing, and could perhaps be implemented in a way as simple as something like the following:

```INI
; Let's say that this is the contents of a file called `Settings.ini`, which would need to be placed
; in the same directory as a given instance of the d3d8to9 version of `d3d8.dll`.

[General]
; The next line would correspond to directly instantiating the `MultiSampleType` field for the used
; swapchain's `PresentParameters` struct with a value of `D3DMULTISAMPLE_4_SAMPLES`.
MultiSampleType=4
```

**Comment by crosire** [comment]
This is not really in the scope for d3d8to9, which is trying to reproduce the exact same behavior games show in D3D8 in D3D9. You can however use a D3D9 wrapper which supports overwriting present parameters on top of d3d8to9 to do this. Probably can even force it via the driver control panel.

**Comment by Akira13641** [comment]
> Probably can even force it via the driver control panel.

That does work sometimes, but at least on Nvidia cards it generally relies on specific "antialiasing flags" for a given game's driver profile, and simply does nothing at all if no such flags happen to exist.

If it's outside the scope of the project though, that's understandable. Thanks for taking the time to read this, anyways.
