### ISSUE TITLE
Direct3D 7 to 9 wrapper

### ISSUE THREAD

**Issue by Kappa971** [crosire/d3d8to9#137]
Hi. A D3D7to9 wrapper would be useful, especially when integrated into Ultimate ASI Loader, for games like Hitman Codenamme 47.
Speaking specifically of Hitman Codenamme 47, it would be useful to be able to use this widescreen fix (http://ps2wide.net/pc.html#h47) together with a wrapper. The only way currently is to use this widescreen fix with dgVoodoo2 (which corrupts the game text anyway) and Ultimate ASI Loader renamed to dsound.dll. The problem is that this doesn't allow you to use 3D audio and EAX restoration software  like DSOAL.

**Comment by crosire** [comment]
This is not in the scope or planned for this project unfortunately.
