### ISSUE TITLE
Popup message upon starting the game

### ISSUE THREAD

**Issue by Riccardoman** [crosire/d3d8to9#140]
"ENBseries 0.076a for black mesa, for more info......"
Is it really necessary?

**Comment by crosire** [comment]
This is not caused by d3d8to9, but by ENBseries, which is a different project and not affliated with d3d8to9.

**Comment by Riccardoman** [comment]
I'm very sorry I had a d3d9.dll floating around that evidently was a leftover of ENB my bad
