### ISSUE TITLE
Mafia The City Lost Heaven

### ISSUE THREAD

**Issue by Dantec116** [crosire/d3d8to9#144]
Hello! I use Widescreen Fix for Mafia 1 fps keeps stable at 60, but shadows flicker. I connect your converter
for the appearance of shadows, the fps begins to fluctuate 58-61 the image twitches.

**Comment by Dantec116** [comment]
The frame rate issue has been resolved. Installed Widescreen fix, renamed d3d8.dll from it to dinput8.dll. Connected enb converter for Mafia. And I installed the Riva Tuner program, set the screen refresh rate to 60 fps in it. As a result, the game began to hold frames stably, the shadows do not flicker. So everything turned out okay.

**Comment by elishacloud** [comment]
I recommend we reopen this.  @ThirteenAG mentioned this issue [here](https://github.com/crosire/d3d8to9/issues/142#issuecomment-1108944978).  This is an issue with d3d8to9 that does not exist with the enb converter.  We should figure out what enb converter does that fixes this issue.
