### ISSUE TITLE
Max Payne - WS Fix not working

### ISSUE THREAD

**Issue by Beats24-7** [crosire/d3d8to9#146]
Hi there,
I have been using your d3d8.dll to be able to start Max Payne again. I am using the integrated graphics of my Ryzen APU (5700G) and the game is only starting with your dll. Otherwise, the game's options menu always starts in the background and is not visible, only in the task manager. However, the Widescreen fix is not working with this .dll. Is there any way to fix this? Thanks in advance!

**Comment by elishacloud** [comment]
The Widescreen fix is just loaded via an ASI file.  You can use the [Ultimate-ASI-Loader](https://github.com/ThirteenAG/Ultimate-ASI-Loader) with a `d3d9.dll` file to load the Widescreen fix ASI.

**Comment by Beats24-7** [comment]
Thanks for your help. Unfortunately, I still cannot get it to work. I downloaded the d3d9.dll and also the ASI loader d8input.dll and put it in the game directory. Still no WS. I have the WS fix from https://github.com/ThirteenAG/WidescreenFixesPack/releases/tag/mp2. This WS fix includes a d3d8f.dll I cannot use because the game doesn't start with my AMD iGPU. 

Thanks again

**Comment by Beats24-7** [comment]
Never mind, I was able to fix it! :)

**Comment by Beats24-7** [comment]
Never mind, I was able to fix it :)
