### ISSUE TITLE
Fellowship of the Ring black screen on startup/uncapped frame rate

### ISSUE THREAD

**Issue by Chip-Biscuit** [crosire/d3d8to9#162]
Hi there is an issue with the game Lord of the Rings Fellowship of the Ring that I hope you could look into. The game boots up with AMD graphics card fine but booting up anything else (nvidia or Intel) it just boots to black screen and nothing else happens.

Also the game has an uncapped frame rate which can reach 1000fps. This can’t be capped or v-sync enabled in any graphics card control panel.

Any help with these issues would be greatly appreciated.

**Comment by MiraakThuri** [comment]
Did you managed to fix it without 3DAnalyse ?
