### ISSUE TITLE
Failed to Load d3dx9_43.dll

### ISSUE THREAD

**Issue by ElG7dod** [crosire/d3d8to9#169]
The program requires me to install DirectX Even Though I've Installed DirectX from Microsoft website and have the DLL on my System32, and yet I get the same error
![generals_vFUM3LPVIV](https://github.com/crosire/d3d8to9/assets/60365002/9ba9ffa7-79cc-4453-b560-89c8473be494)
I've Tried With And Without Gentool, Even Played with the Compatibility Settings, and Clean Installed my Windows and Game Installations too! Help Would be Much Appreciated!

**Comment by HerMajestyDrMona** [comment]
It usually happens when there are "invasive" programs, such as AVG Tune Up installed. They often change the working directory of the launched programs, so that they're unable to find the required DLLs.

Did you install the DirectX Runtime exactly from the link that this d3d8to9 message box is showing?

**Comment by ElG7dod** [comment]
> It usually happens when there are "invasive" programs, such as AVG Tune Up installed. They often change the working directory of the launched programs, so that they're unable to find the required DLLs.
> 
> Did you install the DirectX Runtime exactly from the link that this d3d8to9 message box is showing? Just to confirm, please try installing one from here: https://www.microsoft.com/en-us/download/details.aspx?id=35

first thing i did after reinstalling windows is downloading directx from this link, could the problem be from invasive programs if that's the case?

**Comment by ElG7dod** [comment]
Which One of These Installed Programs would you think to be the culprit?
![Screenshot 2024-04-06 at 18-25-54 Report of DESKTOP-VDL6T9N](https://github.com/crosire/d3d8to9/assets/60365002/59f7533a-84b1-462f-9447-68c84a78f2ed)

**Comment by elishacloud** [comment]
Try copying the following two files from your System32/SysWOW64 folder into the game folder where you put d3d8.dll:

D3DX9_43.dll
D3DCompiler_47.dll

**Comment by ElG7dod** [comment]
> Try copying the following two files from your System32/SysWOW64 folder into the game folder where you put d3d8.dll:
> 
> D3DX9_43.dll D3DCompiler_47.dll

still the same problem

**Comment by elishacloud** [comment]
You may have a bad copy of the dlls.  Also, you could also try these two files (note the different name):

D3DX9_43.dll
D3DCompiler_43.dll

Alternatively, you could try my [dxwrapper](https://github.com/elishacloud/dxwrapper) that removed the reliance on external dll.

**Comment by ElG7dod** [comment]
> You may have a bad copy of the dlls. Also, you could also try these two files (note the different name):
> 
> D3DX9_43.dll D3DCompiler_43.dll
> 
> Alternatively, you could try my [dxwrapper](https://github.com/elishacloud/dxwrapper) that removed the reliance on external dll.

Still the same problem, and the program seems a bit complicated. Could you help me with a guide or something?

**Comment by ElG7dod** [comment]
It works perfectly, but I am having trouble running it with Gentool. ☹

**Comment by ElG7dod** [comment]
> You may have a bad copy of the dlls. Also, you could also try these two files (note the different name):
> 
> D3DX9_43.dll D3DCompiler_43.dll
> 
> Alternatively, you could try my [dxwrapper](https://github.com/elishacloud/dxwrapper) that removed the reliance on external dll.

The dxwrapper works fine, but I am having trouble running it with Gentool. ☹

**Comment by ElG7dod** [comment]
> > You may have a bad copy of the dlls. Also, you could also try these two files (note the different name):
> > D3DX9_43.dll D3DCompiler_43.dll
> > Alternatively, you could try my [dxwrapper](https://github.com/elishacloud/dxwrapper) that removed the reliance on external dll.
> 
> The dxwrapper works fine, but I am having trouble running it with Gentool. ☹

Update: I didn't use the d3d8.dll from stub folder and instead did the following in dxwrapper.ini
![image](https://github.com/crosire/d3d8to9/assets/60365002/15baa170-ca9f-47d3-8961-83f1063af948)
but the DirectX Error is Bugging me, It'd be Great to Know The Source of the Problem

**Comment by elishacloud** [comment]
I don't know anything about Gentool.  But you can exclude it from dxwrapper by using the `ExcludeProcess` option.  Just add the name of the Gentool process there.

**Comment by HerMajestyDrMona** [comment]
I don't know how Gentol works, but if it's installed to a different folder than the game folder, and if you choose the game .exe later, then the working directory where the game starts might be set to the one where Gentol is, instead of where the game is, and that's why it doesn't see copied DLLs (?).

**Comment by ElG7dod** [comment]
I solved the Gentool problem, but I still need to find a solution for the previous DirectX error.

**Comment by elishacloud** [comment]
Not sure about the DirectX error.  Something wrong on your computer.  The only thing I can say is that you may need to install the DirectX9 SDK.

https://www.microsoft.com/en-in/download/details.aspx?id=6812
