### ISSUE TITLE
Missing textures in Hitman 2 Silent Assassin

### ISSUE THREAD

**Issue by elishacloud** [crosire/d3d8to9#17]
There seems to be missing textures on [Hitman 2 Silent Assassin](https://www.gog.com/game/hitman_2_silent_assassin) when using this wrapper/converter.

Here is what I get with [d3d8to9](https://github.com/crosire/d3d8to9):
![hitman2_d3d8tod9](https://cloud.githubusercontent.com/assets/25625456/25559308/11d56066-2cec-11e7-8c71-2675e21c87a5.png)

Here is what it is supposed to look like:
![hitman2](https://cloud.githubusercontent.com/assets/25625456/25559312/22e401b4-2cec-11e7-9931-51a6b7cba461.png)

I think this problem is different than the problem with [Rayman 3: Hoodlum Havoc](https://github.com/crosire/d3d8to9/issues/14) because when I try other converters, like the one [here](http://enbdev.com/convertor_dx8_dx9_v0035.htm), it works fine.  I am hoping someone can look into this as I need this converter to play the game in Windows 10.

**Comment by CookiePLMonster** [comment]
Have you tried comparing pix frames from this wrapper and the one from Boris/ENBSeries? While those are useless for anyone but you (frames can't be viewed from a PC with a different driver/GPU model), maybe you'll spot something obvious in the render states (or texture sampler settings) for 47's draw call.

**Comment by elishacloud** [comment]
Thanks for the suggestion!  However I an new to DirectX programming (and C/C++ programming for that matter).  I am not sure how to compare pix frames.  I don't have the source code for the Boris/ENBSeries converter.

**Comment by CookiePLMonster** [comment]
You'd need to use it to capture frames from ingame and then most likely compare render states during the draw call - no need for the source.

**Comment by elishacloud** [comment]
Ok, I started looking at this in PIX for Windows using this guide [here](https://blogs.msdn.microsoft.com/manders/2006/12/15/a-painless-introduction-to-pix-for-windows/).  So far I have found three differences between d3d8to9 and the Boris/ENBSeries converter.

1. In the `SetVertexShader` function it seems that the Boris/ENBSeries converter calls `SetFVF` and `SetVertexDeclaration` before it calls `SetVertexShader`.  Whereas d3d8to9 calls them in reverse order.

2. In the `SetRenderTarget` function the Boris/ENBSeries converter does not call `Release` and only calls `AddRef` once.  Whereas d3d8to9 calls `Release` and calls `AddRef` more than once.

3. In the frame I captured the Boris/ENBSeries converter called `GetRenderTarget` as the very first call and then `GetDepthStencilSurface` as the third call, whereas these calls were completely missing from d3d8to9.

The first two items were easy to change.  However for the third item, it seems like d3d8to9 is missing a call to `GetRenderTarget` and `GetDepthStencilSurface`.  But I am not sure how to add these calls.

I did take a quick look at the `GetRenderTarget` and `GetDepthStencilSurface` functions in d3d8to9 and I noticed that neither of these call out to their D3D9 equivalent.  When I manually added the `GetRenderTarget` and `GetDepthStencilSurface` functions then the calls for d3d8to9 and Boris/ENBSeries converter were exactly the same.  However this did not solve the issue.  Probably because when I called `GetRenderTarget` and `GetDepthStencilSurface` I just threw away their return results.

Anyways I think the problem is in here somewhere, but I am not quite sure how to fix it.  Is it possible that there are multiple render targets in this game and d3d8to9 can only handle one?

**Comment by CookiePLMonster** [comment]
This doesn't seem to be the case. `GetRenderTarget` and `GetDepthStencilSurface` don't call their d3d9 equivalents because the emulated device seems to cache those by itself.

Looks like d3d8 can't handle multiple render targets either (notice the absence of `Index` parameter in d3d8's `GetRenderTarget`). The issue is puzzling.

**Comment by elishacloud** [comment]
This is the same issue as described in [Indiana Jones And The Emporer's Tomb missing textures](https://github.com/crosire/d3d8to9/issues/25) issue.  The solution can be found in the comment [here](https://github.com/crosire/d3d8to9/issues/25#issuecomment-312400311).

**Comment by elishacloud** [comment]
Fixed with pull [#27](https://github.com/crosire/d3d8to9/pull/27).  Closing.
