### ISSUE TITLE
Create dll d3d8 vgvoodoo 2 for use with reshade

### ISSUE THREAD

**Issue by AngelDavil88** [crosire/d3d8to9#171]
Hi, I have a problem with House of the dead 3 which basically uses directx 8 (I have directx 12) and the only way to not have the missing textures in the game is to use vgvoodoo 2. So far so good, the problem is that I use the sinden lightgun and the white border does not appear. I tried to use reshade and insert your dll (8 to 9) but then in the game I have problems with the textures because it only works with the dgvoodoo dll. Is it possible to modify the dgvoodoo dll from v8 to v9 and then use it on reshade for the game in question?

**Comment by crosire** [comment]
ReShade works just fine with dgVoodoo2, just need to install it for DirectX 11, since that is what dgVoodoo2 translates to.

**Comment by De-M-oN** [comment]
Or change dgvoodoo2's output mode to DirectX 12. It can do that too and is in some games a lot of more fps.
In Need for Speed Hot Pursuit 2 even twice the fps over DX11.
