### ISSUE TITLE
GTA3 on WinXP (SP3): .exe launch error

### ISSUE THREAD

**Issue by Balrogg112** [crosire/d3d8to9#172]
- OS: WinXP (SP3) 32bit (of course never connected to internet)
- latest DirectX9 version compatible with WinXP succesfully installed
- DirectX Runtime mentioned in https://github.com/crosire/d3d8to9/issues/169#issuecomment-2041046254 succesfully installed
- GPU: Nvidia GT630 with driver 368.81 (latest for this GPU compatible with the OS)
- OS and software (also other dx8 and dx9 games) are running fine
- no antivirus software or similar like malware protection software installed

Issue: When starting the game without the additional .dll, the game runs without any problem. After i add the d3d8.dll (v 1.12) into the main folder and click on the gta.exe, the following error appears and the game won't launch at all:

"gta3.exe error - NtCreateFile-API failed. [...]"

Original error message (german language OS): "NtCreateFile-API ist fehlgeschlagen. Dieser Fehler sollte keiner Anwendung zurückgegeben werden, da er ein Platzhalter für den Windows-Redirector ist, damit dieser seine internen Fehlerzuordnungsroutinen verwenden kann."

Please help! :)

**Comment by crosire** [comment]
d3d8to9 isn't build with Windows XP support. If you need that, you'll need to build it yourself with no later than Visual Studio 2017 using the `Visual Studio 2017 - Windows XP (v141_xp)` toolset.
