### ISSUE TITLE
Is this the plugin that came with the Project 64?

### ISSUE THREAD

**Issue by Philgamerk98** [crosire/d3d8to9#178]
Hi. I am trying to rip textures with this thing but the dump all textures button is not working for me! the one Im using is the one that comes with the 2.3 version of project 64. I don't use the current version because I hate waiting 30 seconds just to play my favorite n64 games and Im not willing to support it unless they decide to take down that stupid 30 second timer. 

Lemmy is a good alternative but doesn't dump everything at once so I still need the Jabo to  work but right now its not dumping textures for me and Im trying to dump the flowers and plants with Conker Bad Fur Day.

**Comment by Philgamerk98** [comment]
So you closed this without answering my question? what a lazy way to answer.

**Comment by CookiePLMonster** [comment]
That's because a quick glance at this project's ReadMe file would have revealed that it has nothing to do with console emulators.

**Comment by crosire** [comment]
Sorry, I honestly thought this was AI generated text, none of what was mentioned had anything to do with d3d8to9.

**Comment by Philgamerk98** [comment]
What kind of plugin is this? or was I misinformed by the name of your app or whatever it is? Im just trying to find the Rice plugin for the N64 emulator but none of those versions I found are any of the one I used. So I guess Im barking at the wrong tree here. Sorry if I bothered you!

**Comment by Philgamerk98** [comment]
> That's because a quick glance at this project's ReadMe file would have revealed that it has nothing to do with console emulators.

I honestly don't understand what this is but thanks for the heads up! I only wish there better ways to rip textures from complicated n64 games instead of that worthless pos Lemmy plugin. :(
