### ISSUE TITLE
Crash - Unable to launch exe with d3d8.dll

### ISSUE THREAD

**Issue by LuxInno** [crosire/d3d8to9#29]
Printscreen: http://prntscr.com/fpukbm

Verison: 3.0.0 downloaded from the website.

Any ideas what could be causing this?

PC: Windows 8 Pro, DX End User Runtime said its up to date, so dx9.0c is on the system.

**Comment by Karaulov** [comment]
3.0.0 from reshade website requere:
Visual C++ redistributable
Windows Vista+

Try to build for WinXP + static lib's

**Comment by elishacloud** [comment]
Can you give a little bit more information about the crash?  What exe file are you using?  What are you trying to do?

**Comment by crosire** [comment]
Closing this until further information is provided.
