### ISSUE TITLE
HOW DO I USE D3D8TO9

### ISSUE THREAD

**Issue by toddthetrans** [crosire/d3d8to9#37]
I had some trouble when trying to use d3d8to9. I used visual studio 2017, but it didn't open the .dll file that came with the d3d8to9 download. Also, directx user runtime didnt install for me. I use windows 7. All i'm trying to do is run my older games with Reshade 3. Can someone give me some CLEAR instructions on how to use d3d8to9?

**Comment by HerMajestyDrMona** [comment]
You can't open the compiled .dll file with the Visual Studio.
* If you want to open the source code of d3d8to9 with Visual Studio:
1. Go to: https://github.com/crosire/d3d8to9 and click on the green "Clone or download" button, then "Download ZIP".
2. Unpack the downloaded .zip file to a new folder, and then open file: d3d8to9.sln

*If you just want to use the d3d8to9 with some old game:
1. Make sure that the game you want to play uses DirectX 8. You can find those information by google.
2. Go to: https://reshade.me/d3d8to9 and click on the "Download" button.
3. Copy the downloaded d3d8.dll file to the root folder of your game. This folder should usually contain the .exe file that launches game. Windows explorer might ask you to overwrite an existing d3d8.dll file. If you can't find the location of the game root folder, but you have a desktop icon that launches game - click the right mouse button on this icon, and then "Open file location" from the list.
4. Done! The game will load d3d8to9 and convert DX8 API calls to Direct3D 9 ones.
