### ISSUE TITLE
Transparent Vehicles In True Crime: New York City 

### ISSUE THREAD

**Issue by DisguisedD** [crosire/d3d8to9#44]
The Game now works with the latest release of d3d8to9. However, All of the vehicles In the Game seem to be rendered Incorrectly.

![incorret](https://user-images.githubusercontent.com/31418836/29789458-08765b5a-8c2e-11e7-8df2-816e4ed7d39b.jpg)

As Opposed to: 

![correct](https://user-images.githubusercontent.com/31418836/29789457-085fffea-8c2e-11e7-8f22-25c6130a4553.jpg)

Though The Game Is Playable, I thought It wouldn't hurt to Issue an Issue.

EDIT: The Issue affects cars at proximity only.

Close:
![close](https://user-images.githubusercontent.com/31418836/29790070-401e8fda-8c30-11e7-961e-85e35fb69540.jpg)

Closer:
![closer](https://user-images.githubusercontent.com/31418836/29790069-40055f56-8c30-11e7-9430-1da92bcd596a.jpg)

Hint: Cars at proximity are reflective.

**Comment by elishacloud** [comment]
Hello @DisguisedD, I found 3 separate issues here, one issue with `CreateVertexDeclaration` and two issues with `CreatePixelShader`.  I created some updates that should resolve most of the issues.

Try with this update and let me know how it works: [d3d8.zip](https://github.com/crosire/d3d8to9/files/1385238/d3d8.zip)

**Comment by DisguisedD** [comment]
Hello @ElishaCloud, Cars are not rendered correctly with the updated d3d8.dll file.

Without D3D8.dll:
![without](https://user-images.githubusercontent.com/31418836/31583117-7c536fb2-b18c-11e7-8357-ca649377a259.png)


With D3D8.dll:
![with](https://user-images.githubusercontent.com/31418836/31583143-95dfc57a-b18c-11e7-9dad-5f8055392d0b.png)
