### ISSUE TITLE
PUBG: Crashes with Dxtory

### ISSUE THREAD

**Issue by SkippTekk** [crosire/d3d8to9#51]
So, i have been using Dxtory for a long time. and the game likes to crash before it starts. i have the latest version of Shaders. But i found a temp salution. Load game first, then load Dxtory. no crash logs yet to be found..

Maybe im looking at the wrong place?

Dxtory Version: 2.0.142
Reshade 3.0.8

**Comment by Keith94** [comment]
You might be looking for ReShade repository: https://github.com/crosire/reshade/issues

**Comment by SkippTekk** [comment]
Crap... my mistake!
