### ISSUE TITLE
[Silent Hill 2] Bizarre Text Error

### ISSUE THREAD

**Issue by scoutrw** [crosire/d3d8to9#52]
i got silent hill 2 up 'n workin fine but today out of nowhere it became very estranged

https://i.gyazo.com/734c744ddb6283ddf6ced89dac229c70.mp4

here are what my silent hill 2 files look like
https://i.gyazo.com/93054759c2d569167afe2fb3d54d8c1b.png

scripts
https://i.gyazo.com/77d0402df6973867dee0055b99f1cbe7.png

data
https://i.gyazo.com/c174b88aa9677b25889297a41d92a570.png

this is very infuriating honestly and it makes me Angery, please come up with a solution quick if you can and are willing to. other things to note are that the sound does not work yet CGI cutscene sounds do? and the loading screen is just filled with question marks and whatnot

**Comment by jdkubiak** [comment]
Looking at your `scripts\` folder if you are going to use the [LoadWine ](https://github.com/elishacloud/LoadWineD3D-ASI)files you need to have WineD3D's files in the `scripts\` folder as well. 

As per its [installation instructions](https://github.com/elishacloud/LoadWineD3D-ASI#installation): 

> Copy the WineD3D dll's into the ASI 'scripts' folder. Usually this will be the wine3d.dll, libwine.dll and one or more of the following: d3d8.dll, d3d9.dll, d3d10.dll, d3d11.dll, d3d11core.dll, dxgi.dll or ddraw.dll

However, if you are not using any other `d3d9.dll` file (such as injectSMAA) you currently do not need to use LoadWine. So if you are still having issues then try removing LoadWine from your` scripts\` folder and placing the WineD3D files back into the game's main directory.

If you are still having issues you may have a buggy/bad .exe. Where did you get the `sh2pc.exe` from?

**Comment by elishacloud** [comment]
I am pretty sure this is **not** an issue with [d3d8to9](https://github.com/crosire/d3d8to9).  This is either an issue with WineD3D or with [LoadWineD3D ASI](https://github.com/elishacloud/LoadWineD3D-ASI).  You can see in issue #42 where the issue with d3d8to9 is red tint in the videos and WindeD3D was added to fix that which caused this issue.

**Comment by crosire** [comment]
Closing this for now until OP reports back.
