### ISSUE TITLE
No logging?

### ISSUE THREAD

**Issue by triatomic** [crosire/d3d8to9#59]
Hi, is it possible for the wrapper not to give me any logs ? # #

**Comment by CookiePLMonster** [comment]
You can opt out of any logging by compiling the project with `D3D8TO9NOLOG` defined.

**Comment by triatomic** [comment]
can you please do it ? I don't have the tools nor knowledge in compiling codes.
Sorry for any disturbance.

**Comment by CookiePLMonster** [comment]
[d3d8.zip](https://github.com/crosire/d3d8to9/files/1524379/d3d8.zip)

**Comment by triatomic** [comment]
Much appreciated.
