### ISSUE TITLE
Direct3DDevice8::CreateImageSurface pool

### ISSUE THREAD

**Issue by CookiePLMonster** [crosire/d3d8to9#6]
Currently `Direct3DDevice8::CreateImageSurface` puts the surface in `D3DPOOL_SYSTEMMEM` pool. However MSDN dx8->dx9 migration guide says

```D3DPOOL_SCRATCH will return a surface that has identical characteristics to a surface created by IDirect3DDevice8::CreateImageSurface.```

So is SYSTEMMEM usage here intentional or an oversight?

**Comment by crosire** [comment]
It is intentional. The guide appears to be wrong here, since I did some tests and surfaces created in D3DPOOL_SCRATCH did not actually reflect D3D8 behavior, while D3DPOOL_SYSTEMMEM ones did.

**Comment by CookiePLMonster** [comment]
Fair enough! Seeing how d3d8 partially broke on Win10 (seriously, what the hell is going with its memory footprint on Win10!?!?) it's not so unlikely the docs are wrong. I'll take your word on that :)
