### ISSUE TITLE
Ive asked before. But is there no way we can find out why AA doesn't work with the module?

### ISSUE THREAD

**Issue by LethalManBoob** [crosire/d3d8to9#63]
The games i play like serious sam benefit so heavily from aa that I really cannot go back just for more frames. Is there no way to log what is blocking it?

**Comment by elishacloud** [comment]
@LethalManBoob,  I was able to get AntiAliasing to work using the AA feature [dxwrapper](https://github.com/elishacloud/dxwrapper) while using d3d8to9.  Check out the attached files: [d3d8.zip](https://github.com/crosire/d3d8to9/files/1778000/d3d8.zip)

It does not work with all games but it does work with Serious Sam and Raymond 3 (which looks significantly better with AA!)

Also you can try out [SMAA](http://www.iryoku.com/smaa/) for other games that may not work with dxwrapper's AA.

**Comment by LethalManBoob** [comment]
Thanks man. You're a "serious" help.

**Comment by LethalManBoob** [comment]
Big issue here. AA wont work on serious sam the second encounter. It goes to d3d9 but no aa. I dont know exactly how to correctly install dxwrapper for serious sam. I need help. thanks.

**Comment by elishacloud** [comment]
Yes, the AA in dxwrapper is just trying to force AA on.  Some games won't work if you force it on, so I fail gracefully and just disable AA to ensure the game still runs.  Try [SMAA](http://www.iryoku.com/smaa/).  It should work even if dxwrapper does not.

**Comment by LethalManBoob** [comment]
"but it does work with Serious Sam"

**Comment by LethalManBoob** [comment]
"but it does work with Serious Sam"

This confuses me because it dosen't work on the first encounter ether.

it works with firestarter so i know im not doing anything wrong.

**Comment by elishacloud** [comment]
The issue with Serious Sam (both 1 & 2) is that it requires the backbuffer to be lockable, so this flag `D3DPRESENTFLAG_LOCKABLE_BACKBUFFER` cannot be disabled.  However (as seen [here](https://msdn.microsoft.com/en-us/library/windows/desktop/bb174313(v=vs.85).aspx)) the `D3DPRESENTFLAG_LOCKABLE_BACKBUFFER` flag needs to be disabled before anti-aliasing will work.

Unless you can show me something that works without d3d8to9 that does not work with d3d8to9 then I recommend you close this issue.  If you want anti-aliasing you can use [SMAA](http://www.iryoku.com/smaa/).  It does work with this game, I tested it.

**Comment by LethalManBoob** [comment]
Im very sure that XII (Ubisoft game)  dosent work with d3d8tod3d9. I dont
recall if brothers in arms:

**Comment by LethalManBoob** [comment]
Im very sure that XII (Ubisoft game/UE2) dosent work with d3d8tod3d9.

**Comment by elishacloud** [comment]
I did a fix last night for AA.  Attached is a fixed dll so that you can use AA with d3d8to9.  Can you try with this: [d3d8.zip](https://github.com/crosire/d3d8to9/files/1821492/d3d8.zip)

I tried several games with AA and d3d8to9 using this patched dll and they all worked for me.  If that does not work can you give the exact steps you perform that are not working?

**Comment by LethalManBoob** [comment]
I have since corrected my errors during installation. I found out that I
had to mimic the settings in dxwrapper.ini from my d3d8.ini in order for it
to function. That was the one thing i was missing. it all works fine now
expect for those games i mentioned. Just those two. Code is strange.
Although Firestarter has alt tab crashing issues and the in game animated
tv screens flicker. Antialiasing dosent work on that ether. So strange. it
prevents the game running at 10fps during streaming though. So thats
useful.

**Comment by elishacloud** [comment]
The AA in dxwrapper has some limitations.  It uses standard Direct3D9 MultiSampling a.k.a. Full-Scene Antialiasing (see [here](https://msdn.microsoft.com/en-us/library/windows/desktop/bb173422(v=vs.85).aspx)).  There are two limitations to the standard Direct3D9 MultiSampling:

1. It does not support locking the backbuffer.  See my comments [here](https://github.com/crosire/d3d8to9/issues/66#issuecomment-373892864).
2. It only supports the SwapEffect discard (D3DSWAPEFFECT_DISCARD).  See documentation [here](https://msdn.microsoft.com/en-us/library/windows/desktop/bb172574(v=vs.85).aspx).

However there are games that require backbuffer locking or other swap effects.  For example Serious Sam requires locking the backbuffer.  The SMAA listed above uses shading to do AA after the screen is drawn.  This allows AA to work regardless of the backbuffer or the SwapEffect.  I am planning to switch to this method later when I have time.

If you have other issues or want more data on dxwrapper please close this issue and open an issue on [dxwrapper issues](https://github.com/elishacloud/dxwrapper/issues) page.  We want to keep this forum for d3d8to9 only.

BTW: for the "XII (Ubisoft game/UE2)" game mentioned above do you mean this game [XIII](https://en.wikipedia.org/wiki/XIII_(video_game))?

**Comment by LethalManBoob** [comment]
Unless you are doing SMAA2TX or SMAAS2x i wouldn't bother. It messes up text.

Anyway no i don't have any issues with dxwrapper that dont already have here so i shant be discussing it further. 

And yes i did mean XIII.

**Comment by elishacloud** [comment]
Comments from [here](https://github.com/crosire/d3d8to9/commit/9f1d3670db20269f2bf1a31e4431266c9d121de2#comments):

> Msaa still does not work with serious sam? Am I missing something?
> Through the nvidia drivers.

I tested with [_Serious Sam: The First Encounter_](https://www.gog.com/game/serious_sam_the_first_encounter).  Without d3d8to9 then enabling MSAA via Nvidia Control Panel works fine.  However with d3d8to9 enabling MSAA has no effect.

**Comment by LethalManBoob** [comment]
Great work. It now works perfectly on serious sam first encounter and firestarter. However the second encounter still yields no results.

**Comment by elishacloud** [comment]
> However the second encounter still yields no results.

@LethalManBoob, I believe I found the issue.  Try this update: [d3d8.zip](https://github.com/crosire/d3d8to9/files/4143329/d3d8.zip)

**Comment by LethalManBoob** [comment]
> > However the second encounter still yields no results.
> 
> @LethalManBoob, I believe I found the issue. Try this update: [d3d8.zip](https://github.com/crosire/d3d8to9/files/4143329/d3d8.zip)

I know this is odd. But I swear the issue had since been fixed at some point, but I cannot remember if it was, either way, this most certainly does fix the issue.
