### ISSUE TITLE
Star Wars: Republic Commando crash

### ISSUE THREAD

**Issue by NikoofDeath** [crosire/d3d8to9#66]
Using d3d8to9 with Republic Commando causes a crash after a brief white screen.

d3d8.log gives me this:
```
Redirecting 'Direct3DCreate8(220)' ...
> Passing on to 'Direct3DCreate9':
Redirecting 'IDirect3D8::CreateDevice(0270E010, 0, 1, 000D0F4E, 32, 005FF3B8, 005FF510)' ...
Redirecting 'Direct3DCreate8(220)' ...
> Passing on to 'Direct3DCreate9':
Redirecting 'Direct3DCreate8(220)' ...
> Passing on to 'Direct3DCreate9':
Redirecting 'IDirect3D8::CreateDevice(0270E010, 0, 1, 00120DE4, 70, 0D21FF98, 0D21FF94)' ...
```

I tried on a fresh install, as I was initially using the Republic Commando Graphics Fix, but this did not change anything. I also disabled driver-level graphics settings, as well as RTSS.

**Comment by CookiePLMonster** [comment]
Note to self: game seems to be available on Steam.

http://store.steampowered.com/app/6000/STAR_WARS_Republic_Commando/

**Comment by elishacloud** [comment]
I am using the [gog](https://www.gog.com/game/star_wars_republic_commando) version.  It is on sale this week for only $3.39.  I have done a number of fixes ([here](https://github.com/crosire/d3d8to9/pull/30) and [here](https://github.com/crosire/d3d8to9/pull/32)) on Star Wars Republic Commando.  It works great for me.

Can you tell me the following:
1. What version of the game are you using?
2. What operating system are you using?
3. Is it 32bit or 64bit?
3. What video card do you have?

**Comment by metallicafan212** [comment]
Did you disable FSAA? It crashes the game on startup if it's enabled. To disable it in the ini, go to "Star Wars Republic Commando\GameData\Save", open system.ini in a text editor, under [WinDrv.WindowsClient] there will be a line called FSAA= with a value. If it's not 0, set it to 0.
![image](https://user-images.githubusercontent.com/5996243/37501555-189acd9a-288c-11e8-9f9d-2ccb9dcfcb0e.png)

**Comment by NikoofDeath** [comment]
Disabling FSAA fixed it, thanks!

**Comment by elishacloud** [comment]
Interesting.  I can reproduce the crash now.  I wonder if this is the same thing that is talked about in #63.

**Comment by metallicafan212** [comment]
Yeah, I tried fixing it in the source, but it seems that if MultiSampleType isn't D3DMULTISAMPLE_NONE or D3DMULTISAMPLE_NONMASKABLE, it'll crash. I even was going to make an issue about this until this showed up.

**Comment by metallicafan212** [comment]
I'm going to open an new issue with the information I know.

**Comment by elishacloud** [comment]
It looks like the issue is that the `D3DPRESENTFLAG_LOCKABLE_BACKBUFFER` flag is set which is not supported in Direct3D9 when using multisampling.  See [here](https://msdn.microsoft.com/en-us/library/windows/desktop/bb174313(v=vs.85).aspx)

Once I remove this flag everything works fine.  I also noticed that multisampling is not fully supported in d3d8to9 yet.  I have a pull request almost ready that will fully fix this issue.  I just want to test it on a few more games.

**Comment by elishacloud** [comment]
Attached is a fixed dll for this.  This will allow you to use anti-aliasing: [d3d8.zip](https://github.com/crosire/d3d8to9/files/1821492/d3d8.zip)
