### ISSUE TITLE
Failed vertex shader assembly (mad oFog) + solution

### ISSUE THREAD

**Issue by PatrickvL** [crosire/d3d8to9#81]
The following vertex shader assembly line fails :

    mad oFog /* removed swizzle */, -r3, c150.z, c150.w

It can be fixed by adding this regexp to Direct3DDevice8::CreateVertexShader() :

		SourceCode = std::regex_replace(SourceCode, std::regex("mad (oFog|oPts)(.*), (-?)([crv][0-9]+(?![\\.0-9])), (.+)\\n"), "mad $1$2, $3$4.x /* select single component */, $5\n");

The result is :

    mad oFog /* removed swizzle */, -r3.x /* select single component */, c150.z, c150.w

..which succesfully compiles. (Not sure if the `.x` component is the right choice.)

Test-case : Cxbx-Reloaded, running Morrowind.

**Comment by PatrickvL** [comment]
No time, I'm sorry

**Comment by PatrickvL** [comment]
You neither it seems ;)

**Comment by crosire** [comment]
? It's fixed in https://github.com/crosire/d3d8to9/commit/52a32ef4d8f569ec299bcad13f1a531ce12504c1?
