### ISSUE TITLE
does not work on Win98

### ISSUE THREAD

**Issue by Anths2016** [crosire/d3d8to9#82]
Several games and emulators do not work with this change.

**Comment by crosire** [comment]
Uhm yeah. You need Windows Vista or higher. This is a limitation of the VC++ toolchain.

**Comment by Anths2016** [comment]
Please remove limitation!

**Comment by CookiePLMonster** [comment]
Are you serious? It's up to Visual Studio, not us developers.

May I ask why you need this working on Windows 98?

**Comment by Anths2016** [comment]
I still use Win98.

**Comment by HerMajestyDrMona** [comment]
And what do you need d3d8to9 on Win98 for? DirectX 8 games should work fine there.
