### ISSUE TITLE
Switching out of game via Windows key not working anymore since 1.9.0.0

### ISSUE THREAD

**Issue by Xan05** [crosire/d3d8to9#84]
I've been using this tool with UT2004 without any issues up to 1.8.0, but 1.9.0 broke switching out of the game, as it now crashes with an error message upon reentering the game. Win7 x64, GTX 1060 398.36.

**Comment by elishacloud** [comment]
I am running the [GOG](https://www.gog.com/game/unreal_tournament_2004_ece) version of the game on Windows 10 and it seems to work fine.  I am not getting any crashes when task switching. Which version of the game are you using?

Also can you try this version of d3d8to9: [d3d8.zip](https://github.com/crosire/d3d8to9/files/2195340/d3d8.zip)

**Comment by Xan05** [comment]
I'm using the DVD version. Same issue with the file you posted.

The error message:

UT2004 Build UT2004_Build_[2005-11-23_16.22]

OS: Windows NT 6.1 (Build: 7601)
CPU: GenuineIntel PentiumPro-class processor @ 3410 MHz with 4095MB RAM
Video: NVIDIA GeForce GTX 1060 6GB (9836)

General protection fault!

History: SetViewport <- UD3DRenderDevice::Lock <- UViewport::Lock <- UWindowsViewport::Lock <- UGameEngine::Draw <- UWindowsViewport::Repaint <- UWindowsClient::Tick <- ClientTick <- UGameEngine::Tick <- Level Untitled <- UpdateWorld <- MainLoop <- FMallocWindows::Free <- FMallocWindows::Realloc <- 10910191 0 FArray <- FArray::Realloc <- 0*2 <- FMallocWindows::Free

**Comment by crosire** [comment]
This sounds like `pCurrentRenderTarget` is destroyed when leaving the game and upon reentering d3d8to9 tries to access that in `D3D8Device::SetViewport` (since it is not nullptr) which crashes. We probably need to set `pCurrentRenderTarget` to nullptr in `D3D8Device::Reset`.

**Comment by CookiePLMonster** [comment]
> We probably need to set pCurrentRenderTarget to nullptr in D3D8Device::Reset.

That sounds logical IMO.

**Comment by crosire** [comment]
Try this: [d3d8.zip](https://github.com/crosire/d3d8to9/files/2195697/d3d8.zip).

**Comment by Xan05** [comment]
Issue fixed with the new version.
