### ISSUE TITLE
Screen tearing on Windows 10

### ISSUE THREAD

**Issue by MartinBFFan** [crosire/d3d8to9#85]
Well... I tried the wrapper with several older games and I found out that when I install the wrapper, I get enormous amounts of screen tearing on some of them, which is not present if I play the game without the wrapper. I have observed this mostly on the games made by Novalogic such as Comanche 4 or Delta Force : Black Hawk Down, but can also appear on several other games.

**Comment by elishacloud** [comment]
I have not seen this issue.  However I have not tested any of those particular games either.  I did review [the code](https://github.com/crosire/d3d8to9/blob/2609be5e2b5d905f8a02b9dfff8bf9433ad6ff3d/source/d3d8types.cpp#L115-L156) a bit and it seems we properly handle vsync.

Can you list other games that you see this on?  I don't have Comanche 4 or Delta Force : Black Hawk Down.

**Comment by MartinBFFan** [comment]
I have also noticed it on Star Wars Starfighter and possibly Splinter Cell.

**Comment by MartinBFFan** [comment]
Yes. It works. There is no more screen tearing.
