### ISSUE TITLE
Tony Hawks Pro Skater 3 blue background

### ISSUE THREAD

**Issue by mkultimate** [crosire/d3d8to9#86]
note: congratulations for this great work, this same dll improvement graphics with the emulator of xbox classic would be great improvements to make more compatible graphic errors in the emulator, the good thing about this dll is that I can use the reshader in some games that did not work

blue background
![image](https://user-images.githubusercontent.com/16367065/43219582-5057a792-900d-11e8-8199-9f019d05baf5.png)

without d3d8to9
![image](https://user-images.githubusercontent.com/16367065/43219640-801b1590-900d-11e8-9c24-51b8f7a45d25.png)

**Comment by HerMajestyDrMona** [comment]
It might be related to: https://github.com/crosire/d3d8to9/issues/61

**Comment by mkultimate** [comment]
that's how the videos look

![image](https://user-images.githubusercontent.com/16367065/43224962-8b24a112-901d-11e8-994b-d83ea3837789.png)

![image](https://user-images.githubusercontent.com/16367065/43224998-9fa33784-901d-11e8-92e9-86a0bfc7f382.png)

**Comment by elishacloud** [comment]
If I were to guess I would think this is different than #61.  But it needs further testing.

**Comment by mkultimate** [comment]
with the DLL collapsed the videos start as they are in a corner if I remove the dll the videos start very well without any problem, but what interests me most is the blue background problem the whole game is blue background except the menus

**Comment by elishacloud** [comment]
I believe I fixed this issue.  Try this update: [d3d8.zip](https://github.com/crosire/d3d8to9/files/4143441/d3d8.zip)

**Comment by Vicente7201** [comment]
eh How can I solve the blue background error?
