### ISSUE TITLE
Mega Man X8 (2005 Windows port): d3d8to9 doesn't work in fullscreen

### ISSUE THREAD

**Issue by Zanmato27** [crosire/d3d8to9#90]
I'm having issues with this .dll in that it only seems to work if I'm playing the 2005 Windows PC port of Mega Man X8 in windowed mode yet any anti-aliasing changes I have made doesn't seem to work on fullscreen at all. With this .dll driver, I was able to force 2x2 SGSSAA onto this game and works but only when playing the game in windowed mode.

![megamanx8_2018-12-04_11-51-15](https://user-images.githubusercontent.com/10169555/49458754-6f1e4580-f7bb-11e8-83be-d7bd8d6fe230.png)
Here's an example of the game without any forced anti-aliasing when using d3d8to9 on windowed mode, set resolution of 1280x1024 in the game.

![megamanx8_2018-12-04_11-53-37](https://user-images.githubusercontent.com/10169555/49458819-9248f500-f7bb-11e8-901b-0d123af7b344.png)
Another screenshot of the game featuring the main trio of characters in windowed mode in 1280x1024 while using d3d8to9, but this time using 2x2 Sparse-Grid Super Sampling Anti-Aliasing through Nvidia Profile Inspector, which makes the game appear much higher resolution than it would be possible without d3d8to9 since traditional anti-aliasing methods forced by the video card doesn't work at all with this game.

![megamanx8_2018-12-04_11-54-22](https://user-images.githubusercontent.com/10169555/49458981-f8357c80-f7bb-11e8-8821-19e7de029c3a.png)
And here is a screenshot of the game using those same settings as mentioned in the previous screenshot above but in fullscreen mode, which appears as if I'm not using the settings I placed onto the video card with Nvidia Profile Inspector, even though I am using those settings. The game still looks low resolution as it did without d3d8to9 when running in fullscreen mode.

I am using a NoCD crack to run this game to bypass the CD check this game has and I'm playing what appears to be the 2-disc Korean release of Mega Man X8 for PC but this version does have the option of installing the game in other multiple languages, including English as shown in these screenshots, whereas the single-disc releases (sometimes packaged with Rockman X7 instead) I've seen show up on eBay does not have these multi-lingual options.

EDIT: I am running Windows 10 Home 64-bit with a Nvidia GeForce GTX 750 video card.

**Comment by elishacloud** [comment]
This issue could be the same as #63.

**Comment by Zanmato27** [comment]
That could be it seeing that even after using that d3d8 that was linked with an AA fix hasn't fixed the issue for this game on fullscreen mode unless I missed something.

**Comment by elishacloud** [comment]
@Zanmato27, I tried with the trial version of Mega Man X8 (since I don't have the full version) and the issue does not happen for me with the latest update.  Can you try with this build: [d3d8.zip](https://github.com/crosire/d3d8to9/files/4145820/d3d8.zip)

**Comment by Zanmato27** [comment]
I just tried it and it seems to work fine on Windowed mode but it's hard for me to really tell in Fullscreen Mode since I am only able to run the game at 1280x1024 as the highest supported resolution on my display for this game.

**Comment by elishacloud** [comment]
@Zanmato27, thanks for your comments.  When you configure the game to run in fullscreen mode are you having any issues, or is the game running fine?

**Comment by Zanmato27** [comment]
The game seems to run OK so far.
