### ISSUE TITLE
Forsaken World

### ISSUE THREAD

**Issue by truexfan81** [crosire/d3d8to9#96]
Forsaken World game client doesn't launch at all when this is used.

**Comment by HerMajestyDrMona** [comment]
After quick googling - wasn't this game released in 2011? If so, why would it use Directx 8?

**Comment by elishacloud** [comment]
Are you referring to [this game](https://www.arcgames.com/en/games/forsaken-world)?

It looks like this game does not work with any kind of d3d8 wrapper.  I tried adding a passthrough wrapper that does nothing and the game still does not load.  I tried using passthrough wrappers for other dlls that the game loads, like ddraw, and it worked fine.  It's just d3d8 that has issues with this game.

This game may be doing some kind of hooking or something else with d3d8 that prevents it from loading any d3d8 wrappers.  I believe this is outside the scope of the d3d8to9 project!

_Note: I was able to get d3d8to9 working by using ddraw.dll as the wrapper and then hooking the d3d8.dll APIs.  Though I did find a bug in d3d8to9 with this game.  I will be creating a pull request later with a fix._

**Comment by elishacloud** [comment]
If you want to see d3d8to9 working with this game I have attached a wrapper that will work.  Just unzip this into the Forsaken World folder where the `pem.exe` file exists:  [dxwrapper.zip](https://github.com/crosire/d3d8to9/files/3464291/dxwrapper.zip)
