### ISSUE TITLE
Force VSync and Anisotropic Filtering

### ISSUE THREAD

**Issue by Mitradis** [crosire/d3d8to9#97]
Its not issue, just i dont know how send PM.

Many old games dont have VSync and AF. Is it possible to add support force Vsync and AF in this dll? It would be great.

Without VSync fps is beyond reason and image have horizontal distortion. Without AF old games have VERY blurry textures in the distance.

Thank you in advance.

Maybe it's easy to add to the code. if so tell me what to change. i am very new in C++ (i know C#) but i can.

But need same file D3D9.DLL (for games on DX9.0).

**Comment by Mitradis** [comment]
And one more question: if i try compilling on VS17 i have error stdlib.h not found (but windows SDK 8.1 instaled in VS), but if i change Windows SDK 8.1 > 10.0 i have file size 112KB (original size 120KB).

**Comment by crosire** [comment]
Add ```PresentParams.PresentationInterval = D3DPRESENT_INTERVAL_ONE;``` in this line here to force V-Sync:
https://github.com/crosire/d3d8to9/blob/5cbd8f53d6547b16b4c274a98022da515222030f/source/d3d8to9_base.cpp#L201

**Comment by Mitradis** [comment]
Its great! Only left AF)) Force AF more difficult?

**Comment by donizettilorenzo** [comment]
Up for the request!

**Comment by elishacloud** [comment]
> Force AF more difficult?

Anisotropic filtering is not difficult to set, per se.  However, for it to look right you will likely need to set a differently degree of anisotropy for different textures in a game.  I think this would need to be custom set for each game.  I doubt it's something we could generically build into d3d8to9 for all games.

To see more details see this article [here](https://docs.microsoft.com/en-us/windows/win32/direct3d9/anisotropic-texture-filtering).

**Comment by donizettilorenzo** [comment]
We ask to simply add the feature "force AF 16x". The real problem is this kind of feature would need a proper wrapper-related configuration file, as the VSync forcing. Speaking about that, why d3d8to9 1.9.2 seems to force 60 FPS in windowed mode?

**Comment by HerMajestyDrMona** [comment]
> Speaking about that, why d3d8to9 1.9.2 seems to force 60 FPS in windowed mode (in my tests with Unreal 227i with d3d8 renderer)?

It might be game depended, or Windows 10's "full screen optimizations" might cause it.
To test that, click the right mouse button on the game executable, go to the "Compatibility" tab and check option: "Disable fullscreen optimizations".

The solution to disable the VSync in d3d8to9 is posted here:
https://github.com/crosire/d3d8to9/issues/95#issuecomment-462178962

However, for me it causes more problems than helps. For example in EE2 camera scrolling (moving left/right, top/bottom) is not longer smooth.

**Comment by elishacloud** [comment]
> Speaking about that, why d3d8to9 1.9.2 seems to force 60 FPS in windowed mode

I believe the trouble is that with d3d9 when in windowed mode v-sync is handled by the Desktop Windows Manager (DWM) not by DirectX.  There is not much we can do here.  See this thread [here](https://reshade.me/forum/suggestions/129-v-sync-toggle?start=6#756) for more details.

**Comment by donizettilorenzo** [comment]
*in windowed mode*

**Comment by HerMajestyDrMona** [comment]
`_in windowed mode_ exactly.`
I understood, but using the method from: https://github.com/crosire/d3d8to9/issues/95#issuecomment-462178962
Removes the 60FPS limit, even in the windowed mode: https://i.imgur.com/sWktRL9.png

"Disable fullscreen optimizations" is always worth to test. On my other PC it decides about the 60FPS lock.

**Comment by Mitradis** [comment]
How to force AF to 16x for all textures? we play old games, performance doesn't matter. Just force like driver (he doesn't care about the game).

**Comment by crosire** [comment]
You would have to override the `D3DSAMP_MAXANISOTROPY` value here: https://github.com/crosire/d3d8to9/blob/a1f11b3e51fc8c60d3d000f80735a83560741cf8/source/d3d8to9_device.cpp#L1031.

**Comment by Mitradis** [comment]
> You would have to override the `D3DSAMP_MAXANISOTROPY` value here:
> 
> https://github.com/crosire/d3d8to9/blob/a1f11b3e51fc8c60d3d000f80735a83560741cf8/source/d3d8to9_device.cpp#L1031
> 
> .

what value need set? i replace Value to 16, 21 or 22 they not work.
